### ISSUE TITLE
[BUG] DWR Keeps turning on automatically

### ISSUE THREAD

**Issue by WholesomeMeal** [kamilsss655/uv-k5-firmware-custom#195] opened 2024-08-05 12:54 UTC
Often after a scan, my radio will turn DWR on again. Usually have it set to DW. 

Firmware version: 20.5

UVK5 (8)

**Comment by WholesomeMeal** [comment] 2024-08-06 00:24
Unfortunately I don't have access to the early releases. I'll be happy to tell you once I have it.

**Comment by WholesomeMeal** [comment] 2024-08-07 14:06
Became a Patreon member to test this, yes it still happens. Sometimes when I turn my radio on, DWR is enabled. Despite setting it to DW.

Firmware: v21.4
UKV5(8)

**Comment by WholesomeMeal** [comment] 2024-08-07 14:14
If I scan through one of my lists, press exit (stop the scan), then turn it off - it will turn back on with **DWR enabled every second time.**

**Comment by kamilsss655** [comment] 2024-08-07 15:13
Ok, re-opening this one. :eyes:

**Comment by kamilsss655** [comment] 2024-12-22 22:35
Tested multiple times and could not reproduce with v.21.5. Closing this one. Can be re-opened if someone posts some more detailed steps / video of the issue.

**Closed by kamilsss655** 2024-12-22 22:35 UTC
Labels: bug

**Comment by WholesomeMeal** [comment] 2025-01-10 09:30
Scan through saved memories, turn off then on. Repeat. 
When you turn the radio on again DWR will be enabled.

I have replicated this on 5 different radios.

v.21.7

**Comment by WholesomeMeal** [comment] 2025-01-10 09:34
I have a video of the issue but can't post here because the file size is too large.

**Comment by kamilsss655** [comment] 2025-01-10 15:05
It could be caused by some edge case related to the invalid EEPROM data on your device. That would explain why I could not reproduce it. Can you try factory reset and try to reproduce the issue?

**Comment by WholesomeMeal** [comment] 2025-03-01 06:03
Just tried the reset function (ALL) in the menu. Scanned through default memories. Issue is still there.

**Comment by reppad** [comment] 2025-07-25 18:18
Hi,

I’m having the same issue. I can reproduce it consistently and I’ve tested it with several radios, so I don’t think it’s a case of a corrupted EEPROM. However, it might be some kind of conflict with other parameter values, especially if other users aren’t experiencing the same behavior.

Here is the minimal reproduction scenario:
	1.	Set “RxMode” to “Main TX Dual RX” (aka DW)
	2.	Turn the radio off and on
	3.	Start a scan
	4.	Turn the radio off and on again => the DWR mode is back

Step 2 is mandatory—there must be at least one reboot after enabling DW mode for the bug to occur.

Here’s a video showing the behavior.

https://github.com/user-attachments/assets/591ffa62-cae6-4568-a71b-e9efaca9b586

**Comment by kamilsss655** [comment] 2025-07-26 09:22
Thanks @reppad for more details. I will re-open this issue an try to reproduce.

**Comment by GlydetheSurfer** [comment] 2025-12-03 04:27
having a bugfix locked behind a paywall is unfair to the people who dont have the money to support monthly or hate patreon with a burning passion (like me) because of the fact of paywalls. all the people with no money have to suffer with the bugs and inconveniences. it ISNT right.

**Comment by WholesomeMeal** [comment] 2025-12-03 04:59
@GlydetheSurfer The bug hasn't been fixed yet

**Comment by kamilsss655** [comment] 2025-12-03 11:17
> having a bugfix locked behind a paywall is unfair to the people who dont have the money to support monthly or hate patreon with a burning passion (like me) because of the fact of paywalls. all the people with no money have to suffer with the bugs and inconveniences. it ISNT right.

@GlydetheSurfer you’re welcome to try fixing it yourself, it doesn’t cost anything.

**Comment by GlydetheSurfer** [comment] 2025-12-04 06:30
> > having a bugfix locked behind a paywall is unfair to the people who dont have the money to support monthly or hate patreon with a burning passion (like me) because of the fact of paywalls. all the people with no money have to suffer with the bugs and inconveniences. it ISNT right.
> 
> [@GlydetheSurfer](https://github.com/GlydetheSurfer) you’re welcome to try fixing it yourself, it doesn’t cost anything.

Its fine, I have my solution. >:)
